[project]
name = "lessonsschedulebot"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.13.0"
dependencies = [
    "aiogram==3.23.0",
    "asyncpg>=0.31.0",
    "pydantic-settings>=2.12.0",
    "sqlalchemy==2.0.45",
]


[dependency-groups]
dev = [
    "alembic>=1.17.2",
    "ruff>=0.14.8",
    "ty>=0.0.8",
]


[tool.ruff.format]
indent-style = "space"
quote-style = "double"
